import type { Metadata } from "next";
import { Lora, Caveat } from "next/font/google";
import "./globals.css";
import ProviderProduct from "@/providers/cartProveder";
import Header from "@/components/Header";

const mainFont = Lora({
  variable: "--font-lora-sans",
  subsets: ["latin"],
});


const headerFont = Caveat({
  variable: "--font-caveat-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.variable} ${headerFont.variable} antialiased `}
      >
        <ProviderProduct>
          <Header/>
          {children}
        </ProviderProduct>
      </body>
    </html>
  );
}
