import type { Metadata } from "next";
import { Lora, Caveat, Montserrat } from "next/font/google";
import "./globals.css";
import ProviderProduct from "@/providers/cartProductAmountProvider";
import Header from "@/components/Header";
import CartProvider from "@/providers/cartProvider";

const mainFont = Montserrat({
  variable: "--font-Montserrat-sans",
  subsets: ["latin"],
});

// const mainFont = Lora({
//   variable: "--font-lora-sans",
//   subsets: ["latin"],
// });


// const headerFont = Caveat({
//   variable: "--font-caveat-sans",
//   subsets: ["latin"],
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.variable}  antialiased`}
      >
        <CartProvider>
          <ProviderProduct>
            <div className="flex items-center justify-center dark:bg-black pt-2 pb-2 bg-custom-brown">
              <p className="text-xs tracking-widest">Добро пожаловать в уютный уголок, где всё связано вручную — с душой, заботой и чашкой горячего какао рядом</p>
            </div>
            <Header />
            {children}
          </ProviderProduct>
        </CartProvider>
      </body>
    </html>
  );
}
